# Generated by Django 5.0.4 on 2024-04-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            # name='User',
            # fields=[
            #     ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            #     ('name', models.CharField(max_length=50)),
            #     ('firstname', models.CharField(max_length=50)),
            #     ('email', models.EmailField(max_length=254)),
            #     ('password', models.CharField(max_length=50)),
            # ]
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=79)),
                ('description', models.TextField(max_length=125)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('picture', models.CharField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
