# Generated by Django 5.0.4 on 2024-04-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bubbleTea', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=79)),
                ('description', models.TextField(max_length=125)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
